Macrometacorp/c84j

- pom.xml
- src/main/java/com/c8db/C8DB.java
- src/main/java/com/c8db/C8Database.java
- src/main/java/com/c8db/internal/C8DBImpl.java
- src/main/java/com/c8db/internal/C8DatabaseImpl.java
- src/main/java/com/c8db/internal/InternalC8DB.java
- src/main/java/com/c8db/internal/RestqlImpl.java
- src/main/java/com/c8db/internal/http/HttpConnection.java
- src/main/java/com/c8db/model/DBCreateOptions.java
- src/main/java/com/c8db/model/OptionsBuilder.java
- src/test/java/com/c8db/BaseTest.java
- src/test/java/com/c8db/C8DBTest.java
- src/test/java/com/c8db/UserAuthTest.java
- src/test/java/com/c8db/example/ExampleBase.java
- src/test/java/com/c8db/example/FirstProject.java
- src/test/java/com/c8db/example/graph/AQLActorsAndMoviesExample.java
- src/test/java/com/c8db/example/graph/BaseGraphTest.java
- src/test/java/com/c8db/internal/velocystream/CommunicationTest.java
1. Extended `createGeoFabric()` method to work for all tenants;
2. Adjested the existing JUnit tests
> Fixed createGeoFabric() to work for all tenants

- pom.xml
- src/main/java/com/c8db/entity/UserQueryOptions.java
- src/main/java/com/c8db/internal/RestqlImpl.java
**Purpose**
- Fix restql drop query function (currently `null` is taken as the query name).
- Introduce userId as an UserQueryOptions field.
> Improve RestQL API

- pom.xml
- src/main/java/com/c8db/C8Collection.java
- src/main/java/com/c8db/C8Database.java
- src/main/java/com/c8db/Restql.java
- src/main/java/com/c8db/entity/UserQuery.java
- src/main/java/com/c8db/entity/UserQueryOptions.java
- src/main/java/com/c8db/internal/C8CollectionImpl.java
- src/main/java/com/c8db/internal/C8DatabaseImpl.java
- src/main/java/com/c8db/internal/InternalC8Collection.java
- src/main/java/com/c8db/internal/InternalC8Database.java
- src/main/java/com/c8db/internal/InternalRestql.java
- src/main/java/com/c8db/internal/RestqlImpl.java
- src/main/java/com/c8db/model/IndexOptions.java
- src/main/java/com/c8db/model/OptionsBuilder.java
- src/main/java/com/c8db/model/TTLIndexOptions.java
**Purpose**
- Introduce TTL index options in c84j, to be used with creating TTL indexes using stream workers.
- Make c84j driver compatible with recent c8db API changes
> Make c84j driver compatible with recent c8db API changes

- src/main/java/com/c8db/C8Admin.java
- src/main/java/com/c8db/C8Database.java
- src/main/java/com/c8db/entity/FeaturesEntity.java
- src/main/java/com/c8db/internal/C8AdminImpl.java
- src/main/java/com/c8db/internal/C8DatabaseImpl.java
- src/main/java/com/c8db/internal/InternalC8Admin.java
- src/main/java/com/c8db/model/PersistentIndexOptions.java
**Purpose:**
- [CEP-126] Support deduplicate property with persistent index from CEP
- Release new version with above fix.
- [CEP-131] Feature gate for local collections support
> [CEP-126] Support deduplicate property with persistent index from CEP

- pom.xml
- src/main/java/com/c8db/C8Admin.java
- src/main/java/com/c8db/C8ApiKeys.java
- src/main/java/com/c8db/C8Database.java
- src/main/java/com/c8db/entity/ApiKeyEntity.java
- src/main/java/com/c8db/internal/C8AdminImpl.java
- src/main/java/com/c8db/internal/C8ApiKeyImpl.java
- src/main/java/com/c8db/internal/C8ApiKeysImpl.java
- src/main/java/com/c8db/internal/C8DatabaseImpl.java
- src/main/java/com/c8db/internal/InternalC8Admin.java
- src/main/java/com/c8db/internal/InternalC8ApiKeys.java
- src/main/java/com/c8db/model/ApiKeyOptions.java
- src/main/java/com/c8db/model/OptionsBuilder.java
Introduced the `APIKeys` interface and the `validate()` required by [CEP-158](https://macrometa.atlassian.net/browse/CEP-158) for api keys support in `c8cep`.
> Added the APIKeys interface

- src/main/java/com/c8db/model/CollectionCreateOptions.java
https://macrometa.atlassian.net/browse/C84J-2
> C84J-2 - Change create collection API

- pom.xml
- src/main/java/com/c8db/internal/http/HttpConnection.java
The error message in case of 400 error code is replaced by info message.
> C84J-4 again

- src/main/java/com/c8db/model/CollectionCreateOptions.java
The purpose of this PR is to fix [C84J-5] by exposing `waitForSync` create-collection property through c84j.
> [C84J-5] Expose `waitForSync` create-collection property

- src/main/java/com/c8db/internal/http/HttpConnection.java
The purpose of this PR is to fix [CEP-161] `occasional HTTP 404 logs`.
> [CEP-161] Fix occasional HTTP 404 logs

- pom.xml
- Release `1.1.9`
- Bump to `1.1.10-SNAPSHOT`
> Release 1.1.9

- pom.xml
- src/main/java/com/c8db/C8DB.java
- src/main/java/com/c8db/entity/UserEntity.java
- src/main/java/com/c8db/internal/C8DBImpl.java
For saving events in DB we require useremail.
Currently UserEntity object does not have any attribute for email. This attribute is added as part of this change.
Also the current getUser API only uses demo tenant.
Hence a new API is created to take user and tenant as parameter
> [ALRT-1] : Added email as part of UserEntity

- pom.xml
- src/main/java/com/c8db/internal/InternalRestql.java
$title. This is required for the fix for [CEP-226] : https://github.com/Macrometacorp/c8cep/pull/257
> Set correct deserialize type for UserQueryEntity response deserializer

- src/main/java/com/c8db/internal/InternalC8Dynamo.java
Fixed the setRequestParams method to handle batchWriteRequest
> Fixed the setRequestParams method

- pom.xml
> Release c84j-1.1.21

- src/main/java/com/c8db/C8DB.java
- src/main/java/com/c8db/SecretProvider.java
- src/main/java/com/c8db/internal/C8RemoteSecretProvider.java
- src/main/java/com/c8db/internal/InternalC8DBBuilder.java
- src/main/java/com/c8db/internal/SecretProviderContext.java
- src/main/java/com/c8db/internal/http/HttpConnection.java
- src/main/java/com/c8db/internal/http/HttpConnectionFactory.java
- src/main/java/com/c8db/internal/util/RequestUtils.java
- src/main/java/com/c8db/internal/util/ResponseUtils.java
Users are now able to provide their own way to retrieve the token to communicate with c8 servers.
> Support custom secret providers

- pom.xml
- src/main/java/com/c8db/C8ApiKeys.java
- src/main/java/com/c8db/entity/ApiKeyJwtEntity.java
- src/main/java/com/c8db/internal/C8ApiKeysImpl.java
- src/main/java/com/c8db/internal/InternalC8ApiKeys.java
- src/main/java/com/c8db/model/JwtOptions.java
- src/main/java/com/c8db/model/OptionsBuilder.java
This PR needs for consistency with master branch. Code was merged in PR [!66](https://github.com/Macrometacorp/c84j/pull/66). It includes commits from previous PR , added tag `c84j-1.1.27` and upgraded version in pom file.
> [STRM-353] Dmytro add jwt validation

- pom.xml
> Release 1.1.28

- pom.xml
- src/main/java/com/c8db/C8DB.java
- src/main/java/com/c8db/internal/http/HttpConnection.java
- src/main/java/com/c8db/internal/http/HttpConnectionFactory.java
We need another implementation of cached JWT after JWT-rotation changes that already in `master`.
> STRM-439: Fix cached jwt

- src/main/java/com/c8db/C8Admin.java
- src/main/java/com/c8db/internal/C8AdminImpl.java
- src/main/java/com/c8db/internal/InternalC8Admin.java
**_Duplicate of https://github.com/Macrometacorp/c84j/pull/77 targetting `master`._**
Include access to `GET /_api/limits/enable`.
> c8admin: Add isLimitsEnabled API

- pom.xml
- src/main/java/com/c8db/entity/FeaturesEntity.java
- Add stream_io_connector flag
- Add data mesh integrations feature flag
> Add new feature flags

- src/main/java/com/c8db/entity/FeaturesEntity.java
> Add data mesh integrations feature flag

- src/main/java/com/c8db/internal/http/HttpConnection.java
Corrected the current log message at retry of the request to reflect the current service.
> Correct the misleading log message at retry request.

- pom.xml
- src/main/java/com/c8db/C8ApiKeys.java
- src/main/java/com/c8db/entity/ApiKeyCreateEntity.java
- src/main/java/com/c8db/internal/C8ApiKeysImpl.java
- src/main/java/com/c8db/internal/InternalC8ApiKeys.java
- src/main/java/com/c8db/model/ApiKeyCreateOptions.java
- src/main/java/com/c8db/model/OptionsBuilder.java
The purpose of this PR is to expose a method to create an apiKey.
> [1.1.25] Expose a method to create an apiKey

- src/main/java/com/c8db/C8ApiKeys.java
- src/main/java/com/c8db/entity/ApiKeyCreateEntity.java
- src/main/java/com/c8db/internal/C8ApiKeysImpl.java
- src/main/java/com/c8db/internal/InternalC8ApiKeys.java
- src/main/java/com/c8db/model/ApiKeyCreateOptions.java
- src/main/java/com/c8db/model/OptionsBuilder.java
The purpose of this PR is to expose a method to create an apiKey.
> [master] Expose a method to create an apiKey

- pom.xml
- src/main/java/com/c8db/C8Compute.java
- src/main/java/com/c8db/internal/C8ComputeImpl.java
- src/main/java/com/c8db/internal/C8Executeable.java
- src/main/java/com/c8db/internal/InternalC8Compute.java
- src/main/java/com/c8db/internal/http/HttpConnection.java
- src/main/java/com/c8db/velocystream/Request.java
The method executeFunction(..) should be simplified to `Object` instead of `Collection<Object>` regarding new requrements.
Also added a new parameter `retryEnabled` in `Request` class to make some methods to return result without retries.
> CEP-461: 1.1.25.10

- src/main/java/com/c8db/C8Compute.java
- src/main/java/com/c8db/C8ComputeImpl.java
- src/main/java/com/c8db/internal/C8Executeable.java
- src/main/java/com/c8db/internal/InternalC8Compute.java
- src/main/java/com/c8db/internal/http/HttpConnection.java
- src/main/java/com/c8db/velocystream/Request.java
It is the same PR as for https://github.com/Macrometacorp/c84j/pull/93 but for `master` branch.
Additionally, it includes a commit `Correct the misleading log message at retry request.` that fixes  log message in`retryRequest()` method.
> CEP-461: change response schema fx

- src/main/java/com/c8db/C8Database.java
- src/main/java/com/c8db/C8Redis.java
- src/main/java/com/c8db/entity/CollectionEntity.java
- src/main/java/com/c8db/entity/CollectionModel.java
- src/main/java/com/c8db/internal/C8DatabaseImpl.java
- src/main/java/com/c8db/internal/C8RedisImpl.java
- src/main/java/com/c8db/internal/InternalC8Redis.java
- src/main/java/com/c8db/internal/velocypack/VPackDeserializers.java
- src/main/java/com/c8db/internal/velocypack/VPackDriverModule.java
- src/main/java/com/c8db/internal/velocypack/VPackSerializers.java
- src/main/java/com/c8db/model/C8RedisCreateOptions.java
Added C8Redis class with all required methods for collection except adding/changing/deleting indexes because it is restricted in Redis collection.
> CEP-464: Support Redis collection

- pom.xml
- src/main/java/com/c8db/C8Database.java
- src/main/java/com/c8db/C8Redis.java
- src/main/java/com/c8db/entity/CollectionEntity.java
- src/main/java/com/c8db/entity/CollectionModel.java
- src/main/java/com/c8db/internal/C8DatabaseImpl.java
- src/main/java/com/c8db/internal/C8RedisImpl.java
- src/main/java/com/c8db/internal/InternalC8Redis.java
- src/main/java/com/c8db/internal/velocypack/VPackDeserializers.java
- src/main/java/com/c8db/internal/velocypack/VPackDriverModule.java
- src/main/java/com/c8db/internal/velocypack/VPackSerializers.java
- src/main/java/com/c8db/model/C8RedisCreateOptions.java
Added `C8Redis` class with all required methods for collection except adding/changing/deleting indexes because it is restricted in Redis collection.
> CEP-464: Support Redis colections

- pom.xml
> Release 1.1.30

- pom.xml
- src/main/java/com/c8db/entity/LimitsEntity.java
> [1.1.25] Release data mesh integration limits

- src/main/java/com/c8db/entity/LimitsEntity.java
> Add data mesh integrations limits

- src/main/java/com/c8db/internal/net/FallbackHostHandler.java
Added response code 503 when database server is not reachable. This will help to differentiate between all the other c8DBException generated
> CEP-551: Add response code to C8DBException

- pom.xml
- src/main/java/com/c8db/internal/InternalC8ApiKeys.java
> [CON-1284] Fix fabric name when granting permissions

- src/main/java/com/c8db/entity/LimitsEntity.java
> Update DMI limits

- pom.xml
- src/main/java/com/c8db/entity/LimitsEntity.java
> Rename DMI limits

- src/main/java/com/c8db/C8ApiKeys.java
- src/main/java/com/c8db/C8CEP.java
- src/main/java/com/c8db/C8DB.java
- src/main/java/com/c8db/C8Database.java
- src/main/java/com/c8db/Service.java
- src/main/java/com/c8db/entity/C8StreamWorkerEntity.java
- src/main/java/com/c8db/internal/C8ApiKeysImpl.java
- src/main/java/com/c8db/internal/C8CEPImpl.java
- src/main/java/com/c8db/internal/C8DatabaseImpl.java
- src/main/java/com/c8db/internal/InternalC8ApiKeys.java
- src/main/java/com/c8db/internal/InternalC8DBBuilder.java
- src/main/java/com/c8db/internal/InternalC8StreamWorker.java
- src/main/java/com/c8db/internal/net/HostDescription.java
- src/main/java/com/c8db/internal/util/RequestUtils.java
- src/main/java/com/c8db/model/ApiKeyCreateOptions.java
- src/main/java/com/c8db/model/C8StreamWorkerOptions.java
- src/main/java/com/c8db/model/OptionsBuilder.java
$title. This includes the changes of https://github.com/Macrometacorp/c84j/pull/113 to master branch.
> (master) Add Stream Worker APIs and system API keys support

- pom.xml
- src/main/java/com/c8db/C8DB.java
- src/main/java/com/c8db/C8Database.java
- src/main/java/com/c8db/C8Secret.java
- src/main/java/com/c8db/Service.java
- src/main/java/com/c8db/entity/C8SecretEntity.java
- src/main/java/com/c8db/internal/C8DatabaseImpl.java
- src/main/java/com/c8db/internal/C8SecretImpl.java
- src/main/java/com/c8db/internal/InternalC8Secret.java
- src/main/java/com/c8db/internal/http/HttpConnection.java
- src/main/java/com/c8db/model/C8SecretOptions.java
Added main operations by secret 
- create
- get
- update
- delete
And fixed authentication via password/email with a temporary solution because we will move to JWT-rotation logic
> 1.1.25.19 Added secrets and fix authentication

- pom.xml
- src/main/java/com/c8db/entity/FeaturesEntity.java
- src/main/java/com/c8db/entity/LimitsEntity.java
> [1.1.25.20] Added KMS Gateway and Limits

- src/main/java/com/c8db/C8DB.java
- src/main/java/com/c8db/C8Database.java
- src/main/java/com/c8db/C8Secret.java
- src/main/java/com/c8db/Service.java
- src/main/java/com/c8db/entity/C8SecretEntity.java
- src/main/java/com/c8db/entity/FeaturesEntity.java
- src/main/java/com/c8db/entity/LimitsEntity.java
- src/main/java/com/c8db/internal/C8DatabaseImpl.java
- src/main/java/com/c8db/internal/C8SecretImpl.java
- src/main/java/com/c8db/internal/InternalC8Secret.java
- src/main/java/com/c8db/model/C8SecretOptions.java
It is the same PR as  https://github.com/Macrometacorp/c84j/pull/119 that already approved and merged
Added main operations by secret 
- create
- get
- update
- delete
> KMS-11: Add secret

- pom.xml
- src/main/java/com/c8db/C8Stream.java
- src/main/java/com/c8db/entity/C8StreamDevicePresenceEntity.java
- src/main/java/com/c8db/internal/C8StreamImpl.java
- src/main/java/com/c8db/internal/InternalC8Stream.java
This PR contains the `c84j` changes require to implement device presence support in CEP.
Fixes: [CEP-605]
[CEP-605]: https://macrometa.atlassian.net/browse/CEP-605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (1.1.25)[CEP-605] Add device presence support

- src/main/java/com/c8db/C8Stream.java
- src/main/java/com/c8db/entity/C8StreamDevicePresenceEntity.java
- src/main/java/com/c8db/internal/C8StreamImpl.java
- src/main/java/com/c8db/internal/InternalC8Stream.java
This PR contains the `c84j` changes require to implement device presence support in CEP.
Fixes: [CEP-605]
[CEP-605]: https://macrometa.atlassian.net/browse/CEP-605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (master)[CEP-605] Add device presence support

- pom.xml
- src/main/java/com/c8db/C8Database.java
- src/main/java/com/c8db/Restql.java
- src/main/java/com/c8db/entity/ExecuteUserQueryOptions.java
- src/main/java/com/c8db/internal/C8DatabaseImpl.java
- src/main/java/com/c8db/internal/InternalC8Collection.java
- src/main/java/com/c8db/internal/InternalC8Database.java
- src/main/java/com/c8db/internal/RestqlImpl.java
- src/main/java/com/c8db/model/C8qlQueryOptions.java
This PR contains the c84j changes requires to implement transaction support for the query method in CEP.
Fixes: CEP-606
> CEP-606: Add transaction support to query 

- src/main/java/com/c8db/C8Database.java
- src/main/java/com/c8db/Restql.java
- src/main/java/com/c8db/entity/ExecuteUserQueryOptions.java
- src/main/java/com/c8db/internal/C8DatabaseImpl.java
- src/main/java/com/c8db/internal/InternalC8Collection.java
- src/main/java/com/c8db/internal/InternalC8Database.java
- src/main/java/com/c8db/internal/RestqlImpl.java
- src/main/java/com/c8db/model/C8qlQueryOptions.java
This PR contains the c84j changes required to implement transaction support for the query method in CEP.
Fixes: CEP-606
The same changes were merged to `1.1.25` in PR https://github.com/Macrometacorp/c84j/pull/126
> Add transaction support to query worker and query

- src/main/java/com/c8db/entity/DcInfoEntity.java
- src/main/java/com/c8db/internal/velocypack/VPackDeserializers.java
- src/main/java/com/c8db/internal/velocypack/VPackDriverModule.java
Changed the longitute and latitude fields in response of GET `/datacenter/local` from `String` to `Double`.
> C84J-16: Change lon and lat to Double

- pom.xml
- src/main/java/com/c8db/C8KeyValue.java
- src/main/java/com/c8db/entity/BaseDocument.java
- src/main/java/com/c8db/entity/BlobKeyValue.java
- src/main/java/com/c8db/internal/C8KeyValueImpl.java
- src/main/java/com/c8db/internal/InternalC8KeyValue.java
- src/main/java/com/c8db/internal/http/HttpConnection.java
- src/main/java/com/c8db/internal/util/CURLLogger.java
- src/main/java/com/c8db/internal/velocystream/VstCommunication.java
- src/main/java/com/c8db/velocystream/BinaryRequestBody.java
- src/main/java/com/c8db/velocystream/JsonRequestBody.java
- src/main/java/com/c8db/velocystream/JsonResponseBody.java
- src/main/java/com/c8db/velocystream/MultipartResponseBody.java
- src/main/java/com/c8db/velocystream/Request.java
- src/main/java/com/c8db/velocystream/RequestBody.java
- src/main/java/com/c8db/velocystream/Response.java
- src/main/java/com/c8db/velocystream/ResponseBody.java
- src/test/java/com/c8db/C8KVBlobTest.java
Added new methods 
- `insertBlobKVPairs()`
- `getBlobKVPairs()`, `getBlobKVPairs(options)`
- `getBlobKVPair()`
Added tests in `C8KVBlobTest`
> [C84j-24] Support insert blob in KV store

- pom.xml
- src/test/java/com/c8db/C8DynamoTest.java
Vulnerabilities report in https://macrometa.atlassian.net/browse/STRM-720 in file c8streams.html
> STRM-720: Fix vulnerabilities
