src/main/java/com/c8db/internal/C8Errors.java, src/main/java/com/c8db/internal/http/HttpConnection.java
The purpose of this PR is to get rid of occasional HTTP 4xx stack traces occurring at c84j.  These will be propagated as `C8DBException`s and will get handled at c8cep.
=> [CEP-195] Fix occasional HTTP 4xx stack-traces

pom.xml, src/main/java/com/c8db/internal/http/HttpCommunication.java
Master issue: [STRM-204](https://macrometa.atlassian.net/browse/STRM-204)
In `multi-node`, when host resolution retries exhausted for one request, `c84j` does not resolve hosts for new requests. But it should retry for a new request. Otherwise, `db` object would be unusable after one failed request.
Now `c84j` will reset the retry count before sending the failure response to the first request. So new request will retry the host resolution.
=> STRM-204 Fix host resolution in multi-node setup

pom.xml, src/main/java/com/c8db/entity/DcInfoEntity.java, src/main/java/com/c8db/internal/http/HttpCommunication.java, src/main/java/com/c8db/internal/net/FallbackHostHandler.java
The purpose of this PR is to fix the $title. This is the root cause for extensive NPEs in c8cep logs [1]. This issue is also reported and fixed in the ArangoDB [2] driver itself, and this is a port of that fix.
[1] https://macrometa.atlassian.net/browse/CEP-217
[2] https://github.com/arangodb/arangodb-java-driver/issues/246
=> Fix NullPointerException after 3 connection exceptions using FallbackHostHandler

pom.xml
This PR upgrades the below mentioned dependencies , due to vulnerability issue -
1. org.slf4j:slf4j-api from 1.7.32 to 1.7.36 (https://github.com/Macrometacorp/c84j/pull/50, https://github.com/Macrometacorp/c84j/pull/52)
2. com.fasterxml.jackson.core:jackson-databind from 2.13.1 to 2.13.2.1 (https://github.com/Macrometacorp/c84j/pull/56)
3. com.amazonaws:aws-java-sdk-dynamodb: 1.11.774 -> 1.12.189
com.fasterxml.jackson.core:jackson-databind: 2.13.1 -> 2.13.2.1  (https://github.com/Macrometacorp/c84j/pull/53, https://github.com/Macrometacorp/c84j/pull/51)
=> Synk Fix - Upgrade dependencies to resolve vulnerability issues

src/main/java/com/c8db/C8DB.java, src/main/java/com/c8db/internal/C8DBImpl.java, src/main/java/com/c8db/internal/InternalC8DB.java, src/main/java/com/c8db/model/OptionsBuilder.java, src/main/java/com/c8db/model/UserCreateOptions.java, src/test/java/com/c8db/C8DBTest.java, src/test/java/com/c8db/UserAuthTest.java
The main reason if this PR is to fix `getStreamsAccess` method
now it calls to
```
`curl -X 'GET' \
'https://api-smoke1.eng.macrometa.io:443/_tenant/demo/_fabric/_system/_admin/user/root/database/_system/stream?full=true' \
-H 'accept: application/json' \
-H 'Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjEuNjUxNzM4NzQ0MTI4MTE0ZSs2LCJoYXNoIjo1OTczNjY5MDA3Njk5NzU3NjY5LCJleHAiOjE5NjcwOTg3NDQsImlzcyI6Im1hY3JvbWV0YSIsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UiLCJzdWIiOiJhZG1pbiIsInRlbmFudCI6Il9tbSJ9.n45vbXpEOG5Y4RvrRRlGTdxPqByGEFhK8LOmpaxl_pg='
```
with path that includes `_admin`
it worked well previously and this path set in our `c84j`.
But if change path to our official endpoint(with `_api` in path)  then it will works again
```
curl -X 'GET' \ …
```
=> STRM-327: Fix path and methods for user

pom.xml, src/main/java/com/c8db/model/C8qlQueryOptions.java
**Motivation:**
When reading a large chunk of data, the c8db cursor expires with the error 
**_Exception in thread "main" com.c8db.C8DBException: Response: 404, Error: 1600 - cursor not found_**
This happens because of the default batchSize = 100 and ttl = 30 seconds.
We need to have properties in c84j which allows custom batchSize and ttl to be used for creating cursor.
This PR contains implementation for [CEP-216](https://macrometa.atlassian.net/browse/CEP-216) . The implementation is for enabling the support for creating c8db cursor with custom **batchSize** and **ttl**.
The required cursor can be created as -
`final C8Cursor<Map> c8Cursor = database.query(query, options, type);`
where options contains the custom **batchSize** and **ttl**.
**How this has been Tested ?**
This …
=> CEP-216 Added batchSize and TTL for c8db Cursor

pom.xml, src/main/java/com/c8db/entity/LimitsEntity.java
Added properties `maxCpuSecondsPerMinutePerWorker` and `maxLogsLengthKBPerMinutePerWorker` to LimitsEntity
It needs for usage in limits in `c8cep`
=> CEP-291: Add cpu per worker and logs limits

src/main/java/com/c8db/C8Database.java, src/main/java/com/c8db/C8Stream.java, src/main/java/com/c8db/internal/C8DatabaseImpl.java, src/main/java/com/c8db/internal/C8StreamImpl.java, src/main/java/com/c8db/internal/InternalC8Database.java, src/main/java/com/c8db/internal/InternalC8Stream.java, src/main/java/com/c8db/internal/InternalC8Variables.java, src/test/java/com/c8db/C8StreamTest.java
Streams methods should be the same as an official Streams API.
Some old methods were removed like `skipMessages`, `skipAllMessages`,  `resetCursorToTimestamp`, `resetCursor`.
Added `isLocal` property for methods that use on tenants level(namespace level).
=> Fix all streams methods

src/main/java/com/c8db/internal/C8RemoteSecretProvider.java, src/main/java/com/c8db/internal/SecretProviderContext.java, src/main/java/com/c8db/internal/http/HttpConnection.java
$subject to provide more flexiblity to the custom secret provider implementations.
=> Add more attrs to the SecretProviderContext

src/main/java/com/c8db/SecretProvider.java, src/main/java/com/c8db/internal/C8RemoteSecretProvider.java, src/main/java/com/c8db/internal/http/HttpConnection.java
Most implementations of SecretProvider requires tenant as input to fetchSecret method. So the tenant for token request can be changed dynamically after initializing the driver.
=> [C84J-13] Provide tenant as input to fetchSecret

src/main/java/com/c8db/entity/FeaturesEntity.java
`stream_io_connector` feature flag was missing in the c84j driver.
=> [STRM-340] Add stream_io_connector flag

pom.xml, src/main/java/com/c8db/C8Compute.java, src/main/java/com/c8db/C8ComputeImpl.java, src/main/java/com/c8db/C8DB.java, src/main/java/com/c8db/C8Database.java, src/main/java/com/c8db/Service.java, src/main/java/com/c8db/entity/FxEntity.java, src/main/java/com/c8db/entity/FxMetadataEntity.java, src/main/java/com/c8db/entity/FxType.java, src/main/java/com/c8db/internal/C8DatabaseImpl.java, src/main/java/com/c8db/internal/C8Defaults.java, src/main/java/com/c8db/internal/InternalC8Compute.java, src/main/java/com/c8db/internal/InternalC8DBBuilder.java, src/main/java/com/c8db/internal/http/HttpCommunication.java, src/main/java/com/c8db/internal/http/HttpConnection.java, src/main/java/com/c8db/internal/http/HttpConnectionFactory.java, src/main/java/com/c8db/internal/http/HttpRequestRetryHandler.java, src/main/java/com/c8db/internal/velocypack/VPackDeserializers.java, src/main/java/com/c8db/internal/velocypack/VPackDriverModule.java, src/main/java/com/c8db/model/FxReadOptions.java
For current state of `c8cep` and `c8streams` we need to have a branch from `1.1.25.1` because it is now using there.
Added methods for Compute API
- Fetches a list of all functions. `getFunctions()`
- Get information about function worker. `getInfo(final String name)`
- Fetch information about a edge worker. `getMetadata()`
- Execute a function worker. `executeFunction(String name, Map<String, Object> arguments)`
- added response limit with default value is 1MB.
=> CEP-397: 1.1.25.2

src/main/java/com/c8db/C8Compute.java, src/main/java/com/c8db/C8ComputeImpl.java, src/main/java/com/c8db/C8DB.java, src/main/java/com/c8db/C8Database.java, src/main/java/com/c8db/Service.java, src/main/java/com/c8db/entity/FxEntity.java, src/main/java/com/c8db/entity/FxMetadataEntity.java, src/main/java/com/c8db/entity/FxType.java, src/main/java/com/c8db/internal/C8DatabaseImpl.java, src/main/java/com/c8db/internal/C8Defaults.java, src/main/java/com/c8db/internal/InternalC8Compute.java, src/main/java/com/c8db/internal/InternalC8DBBuilder.java, src/main/java/com/c8db/internal/http/HttpCommunication.java, src/main/java/com/c8db/internal/http/HttpConnection.java, src/main/java/com/c8db/internal/http/HttpConnectionFactory.java, src/main/java/com/c8db/internal/http/HttpRequestRetryHandler.java, src/main/java/com/c8db/internal/velocypack/VPackDeserializers.java, src/main/java/com/c8db/internal/velocypack/VPackDriverModule.java, src/main/java/com/c8db/model/FxReadOptions.java
The PR the same as https://github.com/Macrometacorp/c84j/pull/75 but for `master`
Added methods for Compute API
- Fetches a list of all functions. `getFunctions()`
- Get information about function worker. `getInfo(final String name)`
- Fetch information about a edge worker. `getMetadata()`
- Execute a function worker. `executeFunction(String name, Map<String, Object> arguments)`
- added response limit with default value is 1MB.
=> CEP-397: Add Compute API and response limit

pom.xml, src/main/java/com/c8db/internal/C8ComputeImpl.java, src/main/java/com/c8db/internal/C8DatabaseImpl.java, src/main/java/com/c8db/internal/InternalC8Compute.java, src/main/java/com/c8db/internal/http/HttpConnection.java
Changed path to FaaS Server regarding new requirement by @Anurag Dwivedi :
We  need to call this api:
`_fabric/:fabric/_api/function/invoke/`
in place of the earlier one
`_fabric/_system/_api/compute/fx/invoke/`
@yehan-macrometa - this PR will be merged to `1.1.25` as you done with previous release.
=> [1.1.25] CEP-397: Change path to FaaS Server to `_api/function/invoke`

pom.xml, src/main/java/com/c8db/internal/InternalC8Admin.java, src/main/java/com/c8db/internal/InternalC8Collection.java, src/main/java/com/c8db/internal/InternalC8Database.java, src/main/java/com/c8db/internal/InternalC8Event.java
The issue was that `c8db` removed an old path to Document API.
`/_fabric/{fabric}/document/{collection}/{key}` doesn't work anymore.
We should use `/_fabric/{fabric}/_api/document/{collection}/{key}`
I added `TODO` comment to paths that do not use anymore. And maybe we can delete outdated methods.
=> [1.1.25] STRM-476: Fixed api paths

src/main/java/com/c8db/internal/InternalC8Admin.java, src/main/java/com/c8db/internal/InternalC8Collection.java, src/main/java/com/c8db/internal/InternalC8Database.java, src/main/java/com/c8db/internal/InternalC8Event.java
The issue was that `c8db` removed an old path to Document API.
`/_fabric/{fabric}/document/{collection}/{key}` doesn't work anymore.
We should use `/_fabric/{fabric}/_api/document/{collection}/{key}`
I added `TODO` comment to paths that do not use anymore. And maybe we can delete outdated methods.
=> STRM-476: Fixed api paths

src/main/java/com/c8db/entity/Permissions.java
Description: 
In permissions logic for c8cep and c8streams uses `permission.ordinal()` method for handling access to endpoints. We must not use this method because it can be changed in the future. What sies java documentation:
> Returns the ordinal of this enumeration constant (its position in its enum declaration, where the initial constant is assigned an ordinal of zero). Most programmers will have no use for this method. It is designed for use by sophisticated enum-based data structures, such as `java.util.EnumSet` and `java.util.EnumMap`. 
Solution:
Add `level` method in Permissions class
In the next PRs will be changes `permission.ordinal()` to `permission.level()`  in permissions logic in `c8cep` and `c8streams` repositories.
=> STRM-485: Add level to permissions

pom.xml, src/main/java/com/c8db/C8DB.java, src/main/java/com/c8db/internal/InternalC8DBBuilder.java, src/main/java/com/c8db/internal/http/HttpCommunication.java, src/main/java/com/c8db/internal/http/HttpConnection.java, src/main/java/com/c8db/internal/http/HttpConnectionFactory.java, src/main/java/com/c8db/internal/net/ConnectionFactory.java, src/main/java/com/c8db/internal/net/ConnectionPoolImpl.java, src/main/java/com/c8db/internal/net/DirtyReadHostHandler.java, src/main/java/com/c8db/internal/net/ExtendedHostResolver.java, src/main/java/com/c8db/internal/net/FallbackHostHandler.java, src/main/java/com/c8db/internal/net/HostHandler.java, src/main/java/com/c8db/internal/net/RandomHostHandler.java, src/main/java/com/c8db/internal/net/RoundRobinHostHandler.java, src/main/java/com/c8db/internal/util/HostUtils.java, src/main/java/com/c8db/internal/velocystream/VstCommunication.java, src/main/java/com/c8db/internal/velocystream/VstCommunicationSync.java, src/main/java/com/c8db/internal/velocystream/VstConnectionFactorySync.java, src/main/java/com/c8db/internal/velocystream/internal/VstConnection.java, src/main/java/com/c8db/internal/velocystream/internal/VstConnectionSync.java, src/test/java/com/c8db/internal/HostHandlerTest.java
The issue happens because a single instance of `HostHandler` worked with hosts for multiple services (`Service.C8DB`, `Service.C8STREAMS`, `Service.C8FUNCTION`) It caused an issue because instead of, for example, `C8DB` host it used `C8STREAMS` host. `HostHandler` was constructed to use only got single service. 
Therefore, the solution here is to set only one `service` per `HostHandler`.
What was done:
1. Roll back all changes(2 related latest commits) in all `HostHandler` children`DirtyReadHostHandler`, `FallbackHostHandler`, `RandomHostHandler`, `RoundRobinHostHandler` 
Commit #1 https://github.com/Macrometacorp/c84j/commit/137094273e18a3c5ab14660d3a78a78c627315c0 
Commit #2 https://github.com/Macrometacorp/c84j/commit/48e8ec9bffa9763e5261b2e9d823518e80be3a6f
2. Added `final Service …
=> CEP-458: 1.1.25.8

src/main/java/com/c8db/C8KeyValue.java, src/main/java/com/c8db/entity/C8KVCollectionEntity.java, src/main/java/com/c8db/entity/C8KVEntity.java, src/main/java/com/c8db/internal/C8KeyValueImpl.java, src/main/java/com/c8db/internal/InternalC8KeyValue.java, src/main/java/com/c8db/model/C8KVCountPairsOptions.java, src/main/java/com/c8db/model/C8KVCreateMixin.java, src/main/java/com/c8db/model/C8KVCreateOptions.java, src/main/java/com/c8db/model/C8KVReadGroupsOptions.java, src/main/java/com/c8db/model/C8KVReadKeysOptions.java, src/main/java/com/c8db/model/C8KVReadValuesOptions.java, src/main/java/com/c8db/model/C8KVTruncateOptions.java, src/main/java/com/c8db/model/GroupIdMixin.java, src/main/java/com/c8db/model/OptionsBuilder.java, src/main/java/com/c8db/model/PaginationMixin.java, src/main/java/com/c8db/model/SortMixin.java
Should be added a new method that uses a new endpoint `GET API [/_fabric/{fabric}/_api/kv/{collection}/groups](https://akashj-dxb.eng.macrometa.io/api#/Key%20Value/get__fabric__fabric___api_kv__collection__groups) Get list of groups in collection`
The previous part of the GroupId feature was implemented in PR https://github.com/Macrometacorp/c84j/pull/122
=> STRM-662: Added getGroups methods for KV

pom.xml, src/main/java/com/c8db/C8KeyValue.java, src/main/java/com/c8db/entity/CollectionEntity.java, src/main/java/com/c8db/entity/CollectionType.java, src/main/java/com/c8db/internal/C8KeyValueImpl.java, src/main/java/com/c8db/internal/InternalC8Collection.java, src/main/java/com/c8db/internal/InternalC8Database.java, src/main/java/com/c8db/internal/InternalC8KeyValue.java, src/main/java/com/c8db/model/C8KVCreateBodyOptions.java, src/main/java/com/c8db/model/C8KVCreateOptions.java, src/main/java/com/c8db/model/C8KVDeleteValueOptions.java, src/main/java/com/c8db/model/C8KVDeleteValuesOptions.java, src/main/java/com/c8db/model/C8KVInsertValuesOptions.java, src/main/java/com/c8db/model/C8KVReadValueOptions.java, src/main/java/com/c8db/model/C8KVReadValuesOptions.java, src/main/java/com/c8db/model/C8KVTruncateOptions.java, src/main/java/com/c8db/model/CollectionCreateBodyOptions.java, src/main/java/com/c8db/model/CollectionCreateOptions.java, src/main/java/com/c8db/model/DocumentCreateOptions.java, src/main/java/com/c8db/model/DocumentDeleteOptions.java, src/main/java/com/c8db/model/DocumentExistsOptions.java, src/main/java/com/c8db/model/DocumentReadOptions.java, src/main/java/com/c8db/model/DocumentReplaceOptions.java, src/main/java/com/c8db/model/DocumentUpdateOptions.java, src/main/java/com/c8db/model/OptionsBuilder.java, src/main/java/com/c8db/model/StrongConsistencyMixin.java
Updated the next endpoints in Key Value API: 
- POST `/_fabric/{fabric}/_api/kv/{collection}` Create key-value collection, - added strongConsistency body parameter
- DELETE  `/_fabric/{fabric}/_api/kv/{collection}/value/{key}` Remove key-value pair - added `strongConsistency` query parameter
- DELETE  `/_fabric/{fabric}/_api/kv/{collection}/values` Remove key-value pairs. - added `strongConsistency` query parameter
- GET  `/_fabric/{fabric}/_api/kv/{collection}/value/{key}`  - added `strongConsistency` query parameter
- POST `/_fabric/{fabric}/_api/kv/{collection}/values`  - added `strongConsistency` query parameter
- PUT `/_fabric/{fabric}/_api/kv/{collection}/value`  Set one or more key-value pairs - added `strongConsistency` query parameter
- PUT …
=> C84J-17: Support Strong Consistency

pom.xml, src/main/java/com/c8db/internal/InternalC8KeyValue.java, src/main/java/com/c8db/model/C8KVCountPairsOptions.java, src/main/java/com/c8db/model/C8KVReadKeysOptions.java
Added `strongConsistency` optional query parameter to `kv/count`, `kv/keys` regarding the comment https://macrometa.atlassian.net/browse/C84J-17?focusedCommentId=57873
=> C84J-17: Add strong consistency to countKVPairs, getKVKeys methods

src/main/java/com/c8db/internal/C8Errors.java
Fix `ERROR_STREAM_ALREADY_EXISTS` variable to `1210` in class `C8Errors`.
=> C84J-19: Fix ERROR_STREAM_ALREADY_EXISTS to 1210

pom.xml, src/main/java/com/c8db/internal/C8Errors.java
Fix `ERROR_STREAM_ALREADY_EXISTS` variable to `1210` in class `C8Errors`.
=> [1.1.25] C84j-19: Fix ERROR_STREAM_ALREADY_EXISTS to 1210

pom.xml, src/main/java/com/c8db/C8DB.java, src/main/java/com/c8db/internal/C8Defaults.java, src/main/java/com/c8db/internal/InternalC8DBBuilder.java, src/main/java/com/c8db/internal/http/HttpConnection.java, src/main/java/com/c8db/internal/http/HttpConnectionFactory.java, src/main/java/com/c8db/util/BackoffRetryCounter.java, src/main/java/com/c8db/util/RequestBackoffRetryCounter.java
The issue was because of the next exception:
```
2023-10-19 22:41:59,034877 ERROR StreamHandler.onError(StreamHandler.java:95) - thread_name="C8CEP-T-MHwHnrgAI3DBMwf35fXUQ-.root._system.sw-db-restart3-executor-thread-0" - [AppId: T-MHwHnrgAI3DBMwf35fXUQ-.root._system.sw-db-restart3]  Error in SiddhiApp 'T-MHwHnrgAI3DBMwf35fXUQ-:root:_system:sw-db-restart3' after consuming events from Stream 'ExternlPulsarStream1', com.c8db.C8DBException: Cannot contact any host!. Hence, dropping event 'Event{timestamp=1697755319023, data=[22222], isExpired=false}' com.c8db.C8DBException: Cannot contact any host!?	
at com.c8db.internal.net.FallbackHostHandler.get(FallbackHostHandler.java:50) ~[c84j-1.1.25.23.jar!/:?]?	
at com.c8db.internal.net.DirtyReadHostHandler.get(DirtyReadHostHandler.java:48) …
```
=> [1.25.24] CEP-566: Fix data loss in SW. Add Retry to HttpCommunication

pom.xml, src/main/java/com/c8db/C8DB.java, src/main/java/com/c8db/internal/C8Defaults.java, src/main/java/com/c8db/internal/InternalC8DBBuilder.java, src/main/java/com/c8db/internal/http/HttpConnection.java, src/main/java/com/c8db/internal/http/HttpConnectionFactory.java, src/main/java/com/c8db/util/BackoffRetryCounter.java, src/main/java/com/c8db/util/RequestBackoffRetryCounter.java
The issue was because of the next exception:
```
2023-10-19 22:41:59,034877 ERROR StreamHandler.onError(StreamHandler.java:95) - thread_name="C8CEP-T-MHwHnrgAI3DBMwf35fXUQ-.root._system.sw-db-restart3-executor-thread-0" - [AppId: T-MHwHnrgAI3DBMwf35fXUQ-.root._system.sw-db-restart3]  Error in SiddhiApp 'T-MHwHnrgAI3DBMwf35fXUQ-:root:_system:sw-db-restart3' after consuming events from Stream 'ExternlPulsarStream1', com.c8db.C8DBException: Cannot contact any host!. Hence, dropping event 'Event{timestamp=1697755319023, data=[22222], isExpired=false}' com.c8db.C8DBException: Cannot contact any host!?	
at com.c8db.internal.net.FallbackHostHandler.get(FallbackHostHandler.java:50) ~[c84j-1.1.25.23.jar!/:?]?	
at com.c8db.internal.net.DirtyReadHostHandler.get(DirtyReadHostHandler.java:48) …
```
=> CEP-566: Fix data loss in SW. Add Retry to HttpCommunication

pom.xml, src/main/java/com/c8db/internal/InternalC8DBBuilder.java
Now, the default number of HTTP connections is `1` 
But default should be `20`
=> [1.1.25] C84J-20: Fix default HTTP connections to 20

pom.xml, src/main/java/com/c8db/internal/InternalC8DBBuilder.java
Now, the default number of HTTP connections is `1` 
But default should be `20`
=> C84J-20: Fix default HTTP connections to 20

bin/pom.xml, pom.xml, src/main/java/com/c8db/internal/C8Executeable.java, src/main/java/com/c8db/internal/C8RemoteSecretProvider.java, src/main/java/com/c8db/internal/InternalC8Admin.java, src/main/java/com/c8db/internal/InternalC8Alerts.java, src/main/java/com/c8db/internal/InternalC8ApiKeys.java, src/main/java/com/c8db/internal/InternalC8Collection.java, src/main/java/com/c8db/internal/InternalC8Compute.java, src/main/java/com/c8db/internal/InternalC8DB.java, src/main/java/com/c8db/internal/InternalC8Database.java, src/main/java/com/c8db/internal/InternalC8Dynamo.java, src/main/java/com/c8db/internal/InternalC8EdgeCollection.java, src/main/java/com/c8db/internal/InternalC8Event.java, src/main/java/com/c8db/internal/InternalC8Graph.java, src/main/java/com/c8db/internal/InternalC8KeyValue.java, src/main/java/com/c8db/internal/InternalC8Redis.java, src/main/java/com/c8db/internal/InternalC8Secret.java, src/main/java/com/c8db/internal/InternalC8Stream.java, src/main/java/com/c8db/internal/InternalC8StreamWorker.java, src/main/java/com/c8db/internal/InternalC8VertexCollection.java, src/main/java/com/c8db/internal/InternalRestql.java, src/main/java/com/c8db/internal/http/HttpConnection.java, src/main/java/com/c8db/internal/net/ExtendedHostResolver.java, src/main/java/com/c8db/internal/velocypack/VPackSerializers.java, src/main/java/com/c8db/internal/velocystream/internal/AuthenticationRequest.java, src/main/java/com/c8db/velocystream/Request.java
Was found that c8db.secrets().get() stopped working after upgrading from `1.1.25.x`. The issue was when `Request` class doesn't have `tenant` as a parameter for path then SecretProvider cannot convert service's jwt to user`s jwt because of `tenant == null`
#Solution
is to provide additional parameter `dbTenant` in `C8Executeable` class and insert it into `Request` class.
This fix also fixed workaround for `Functions`:
```
if (tenant != null && !tenant.isEmpty() && service != Service.C8FUNCTION) {
```
=> CEP-658: Fixed SecretProvider for secrets. Removed workaround for fx.

pom.xml, src/main/java/com/c8db/internal/http/HttpCommunication.java, src/main/java/com/c8db/internal/http/HttpConnection.java, src/main/java/com/c8db/internal/net/ConnectionDisposer.java, src/main/java/com/c8db/internal/net/ConnectionPool.java, src/main/java/com/c8db/internal/net/ConnectionPoolImpl.java, src/main/java/com/c8db/internal/net/Host.java, src/main/java/com/c8db/internal/net/HostImpl.java, src/main/java/com/c8db/internal/net/ManagedConnection.java, src/main/java/com/c8db/internal/velocystream/VstCommunication.java
The current implementation caused the connections to expire before they had the chance to be reused if the requests were not frequent. This was causing high latency for Akamai EdgeKV. 
Summarizing the changes: in the connection pool, instead of having an array of connections and cycling through the whole array as new connections are requested, the pool can have a stack of connections. Whenever a new connection is used and is no longer needed, it is returned (disposed) back to the pool and pushed onto the stack of available connections. To return connections back to the pool, the `ManagedConnection` class.
The previous implementation caused the connections to expire before they could be reused if the requests were not frequent. This was causing high latency for Akamai EdgeKV. With the new …
=> C84J-25: Connection pool improvement
